/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.roncolatoandpedro.soulinstruments.ui;

import com.roncolatoandpedro.soulinstruments.dao.DAOFactory; // Importe DAOFactory
import com.roncolatoandpedro.soulinstruments.dao.impl.FornecedorDAOImpl;
import com.roncolatoandpedro.soulinstruments.dao.impl.InstrumentoDAOImpl;
import com.roncolatoandpedro.soulinstruments.dao.impl.ProdutoDAOImpl;
import com.roncolatoandpedro.soulinstruments.dto.Categoria;
import com.roncolatoandpedro.soulinstruments.dto.FornecedorDTO;
import com.roncolatoandpedro.soulinstruments.dto.InstrumentoDTO;
import com.roncolatoandpedro.soulinstruments.dto.ProdutoDTO;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection; // Importe Connection
import java.sql.SQLException;
import java.util.logging.Level; // Importe Level para uso com logger
import java.util.logging.Logger; // Importe Logger

import static java.lang.Long.SIZE;

/**
 *
 * @author AmonA
 */
public class cadastrarProduto extends javax.swing.JDialog {

    private static final Logger logger = Logger.getLogger(cadastrarProduto.class.getName());

    // Instâncias das DAOs
    private ProdutoDAOImpl produtoImpl;
    private InstrumentoDAOImpl instrumentoImpl;
    private FornecedorDAOImpl fornecedorImpl;

    /**
     * Creates new form cadastrarProduto
     * @param parent O Frame pai do diálogo.
     * @param modal Define se o diálogo é modal (bloqueia a interação com a janela pai).
     */
    public cadastrarProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        try {
            // Inicializa as DAOs usando a fábrica de conexões
            Connection connection = DAOFactory.getConexao();
            this.produtoImpl = new ProdutoDAOImpl(connection);
            this.instrumentoImpl = new InstrumentoDAOImpl(connection);
            this.fornecedorImpl = new FornecedorDAOImpl(connection);
        } catch (SQLException e) {
            logger.log(Level.SEVERE, "Erro ao inicializar DAOs para cadastro de produto: " + e.getMessage(), e);
            JOptionPane.showMessageDialog(this,
                    "Erro ao conectar ao banco de dados para o cadastro de produto: " + e.getMessage(),
                    "Erro de Inicialização",
                    JOptionPane.ERROR_MESSAGE);
            // Se a conexão for crítica, você pode querer fechar o diálogo.
            // dispose();
        }

        // Popula o JComboBox com os valores da enum Categoria
        comBoxCategoria.removeAllItems();
        for (Categoria categoria : Categoria.values()) {
            comBoxCategoria.addItem(categoria.name());
        }
        comBoxCategoria.setSelectedIndex(0); // Seleciona o primeiro item por padrão
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jLabel5 = new JLabel();
        txtNome = new JTextField();
        jLabel6 = new JLabel();
        txtMarca = new JTextField();
        jLabel4 = new JLabel();
        comBoxCategoria = new JComboBox<>();
        jLabel11 = new JLabel();
        txtFornecedor = new JTextField();
        jLabel10 = new JLabel();
        txtPreco = new JTextField();
        jLabel12 = new JLabel();
        txtDescricao = new JTextField();
        jLabel9 = new JLabel();
        txtModelo1 = new JTextField();
        jLabel13 = new JLabel();
        txtQuantidade = new JTextField();
        btnSalvar = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new Color(40, 34, 44));

        jLabel5.setBackground(new Color(21, 22, 27));
        jLabel5.setFont(new Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel5.setForeground(new Color(255, 255, 255));
        jLabel5.setText("NOME INSTRUMENTO"); // Alterado de ID para NOME INSTRUMENTO

        txtNome.setBackground(new Color(22, 21, 27));
        txtNome.setForeground(new Color(255, 255, 255));
        txtNome.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new Color(21, 22, 27));
        jLabel6.setFont(new Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel6.setForeground(new Color(255, 255, 255));
        jLabel6.setText("MARCA");

        txtMarca.setBackground(new Color(22, 21, 27));
        txtMarca.setForeground(new Color(255, 255, 255));
        txtMarca.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new Color(21, 22, 27));
        jLabel4.setFont(new Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setForeground(new Color(255, 255, 255));
        jLabel4.setText("CATEGORIA");

        comBoxCategoria.setBackground(new Color(21, 22, 27));
        comBoxCategoria.setForeground(new Color(255, 255, 255));
        comBoxCategoria.setModel(new DefaultComboBoxModel<>(new String[] { "SOPRO", "CORDAS", "PERCUSSAO", "ELETRONICO" }));
        comBoxCategoria.addActionListener(this::comBoxCategoriaActionPerformed);

        jLabel11.setBackground(new Color(21, 22, 27));
        jLabel11.setFont(new Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel11.setForeground(new Color(255, 255, 255));
        jLabel11.setText("FORNECEDOR");

        txtFornecedor.setBackground(new Color(22, 21, 27));
        txtFornecedor.setForeground(new Color(255, 255, 255));
        txtFornecedor.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtFornecedorActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new Color(21, 22, 27));
        jLabel10.setFont(new Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel10.setForeground(new Color(255, 255, 255));
        jLabel10.setText("PRECO");

        txtPreco.setBackground(new Color(22, 21, 27));
        txtPreco.setForeground(new Color(255, 255, 255));
        txtPreco.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new Color(21, 22, 27));
        jLabel12.setFont(new Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel12.setForeground(new Color(255, 255, 255));
        jLabel12.setText("DESCRICAO");

        txtDescricao.setBackground(new Color(22, 21, 27));
        txtDescricao.setForeground(new Color(255, 255, 255));
        txtDescricao.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new Color(21, 22, 27));
        jLabel9.setFont(new Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel9.setForeground(new Color(255, 255, 255));
        jLabel9.setText("MODELO");

        txtModelo1.setBackground(new Color(22, 21, 27));
        txtModelo1.setForeground(new Color(255, 255, 255));
        txtModelo1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtModelo1ActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new Color(21, 22, 27));
        jLabel13.setFont(new Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel13.setForeground(new Color(255, 255, 255));
        jLabel13.setText("QUANTIDADE");

        txtQuantidade.setBackground(new Color(22, 21, 27));
        txtQuantidade.setForeground(new Color(255, 255, 255));
        txtQuantidade.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new Color(202, 207, 214));
        btnSalvar.setForeground(new Color(4, 138, 129));
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnSalvarActionPerformed(evt); // Removido 'throws SQLException'
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(btnSalvar, GroupLayout.PREFERRED_SIZE, 179, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDescricao, GroupLayout.PREFERRED_SIZE, 645, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtPreco)
                                                        .addComponent(jLabel10)
                                                        .addComponent(txtFornecedor)
                                                        .addComponent(jLabel11)
                                                        .addComponent(comBoxCategoria, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(txtMarca, GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(txtNome)
                                                        .addComponent(jLabel5))
                                                .addGap(232, 232, 232)
                                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9)
                                                        .addComponent(txtModelo1, GroupLayout.PREFERRED_SIZE, 215, GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(txtQuantidade, GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel13, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel9))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtModelo1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel13))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtMarca, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtQuantidade, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(jLabel4)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comBoxCategoria, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFornecedor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPreco)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescricao, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(btnSalvar, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 1037, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 621, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // Ação para o campo txtNome (se necessário)
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // Ação para o campo txtMarca (se necessário)
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void comBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxCategoriaActionPerformed
        // Ação para o JComboBox comBoxCategoria (se necessário)
    }//GEN-LAST:event_comBoxCategoriaActionPerformed

    private void txtFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFornecedorActionPerformed
        // Ação para o campo txtFornecedor (se necessário)
    }//GEN-LAST:event_txtFornecedorActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // Ação para o campo txtPreco (se necessário)
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // Ação para o campo txtDescricao (se necessário)
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void txtModelo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelo1ActionPerformed
        // Ação para o campo txtModelo1 (se necessário)
    }//GEN-LAST:event_txtModelo1ActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // Ação para o campo txtQuantidade (se necessário)
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) { // Removido 'throws SQLException'
        // Validação das instâncias DAO
        if (produtoImpl == null || instrumentoImpl == null || fornecedorImpl == null) {
            JOptionPane.showMessageDialog(this, "O serviço de banco de dados não foi inicializado corretamente.", "Erro Interno", JOptionPane.ERROR_MESSAGE);
            logger.log(Level.SEVERE, "DAO(s) nula(s) no btnSalvarActionPerformed. Verifique a inicialização no construtor.");
            return;
        }

        String nomeInstrumento = txtNome.getText().trim();
        String categoria = (String) comBoxCategoria.getSelectedItem();
        String descricao = txtDescricao.getText().trim();
        String modelo = txtModelo1.getText().trim();
        String marca = txtMarca.getText().trim();
        String precoTexto = txtPreco.getText().trim();
        String quantidadeTexto = txtQuantidade.getText().trim();
        String nomeFornecedor = txtFornecedor.getText().trim();

        // Validação de campos vazios
        if (nomeInstrumento.isEmpty() || categoria == null || descricao.isEmpty()
                || modelo.isEmpty() || marca.isEmpty() || precoTexto.isEmpty()
                || quantidadeTexto.isEmpty() || nomeFornecedor.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos!", "Campos Vazios", JOptionPane.WARNING_MESSAGE);
            logger.log(Level.WARNING, "Tentativa de salvar produto com campos vazios.");
            return;
        }

        double preco;
        int quantidade;
        try {
            preco = Double.parseDouble(precoTexto);
            quantidade = Integer.parseInt(quantidadeTexto);
            if (preco < 0 || quantidade < 0) { // Preço e quantidade não podem ser negativos
                JOptionPane.showMessageDialog(this, "Preço e Quantidade não podem ser números negativos.", "Valor Inválido", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Preço e Quantidade devem ser números válidos.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
            logger.log(Level.WARNING, "Erro de formato ao parsear Preço ou Quantidade: " + e.getMessage(), e);
            return;
        }

        try {
            // 1. Criar ou buscar o Instrumento
            InstrumentoDTO instrumento;
            // Primeiro, tenta buscar o instrumento pelo nome
            InstrumentoDTO instrumentoExistente = instrumentoImpl.buscarPorNome(nomeInstrumento);

            if (instrumentoExistente != null) {
                // Se o instrumento já existe, usa ele
                instrumento = instrumentoExistente;
                logger.log(Level.INFO, "Usando instrumento existente: " + nomeInstrumento);
                // Opcional: Atualizar a categoria se for diferente
                if (!instrumento.getCategoria().name().equals(categoria)) {
                    instrumento.setCategoria(Categoria.valueOf(categoria));
                    instrumentoImpl.atualizar(instrumento); // Assumindo que InstrumentoDAOImpl tem um método 'atualizar'
                    logger.log(Level.INFO, "Categoria do instrumento atualizada para: " + categoria);
                }
            } else {
                // Se o instrumento não existe, cria um novo
                instrumento = new InstrumentoDTO();
                instrumento.setNome(nomeInstrumento);
                instrumento.setCategoria(Categoria.valueOf(categoria));
                instrumentoImpl.salvar(instrumento);
                logger.log(Level.INFO, "Novo instrumento cadastrado: " + nomeInstrumento);

                // IMPORTANTE: Após salvar um novo instrumento, você precisa obter o ID gerado
                // Se seu método salvar() não retorna o DTO com o ID, você precisará buscá-lo novamente
                // Idealmente, seu método salvar() deveria retornar o DTO completo com o ID gerado.
                instrumento = instrumentoImpl.buscarPorNome(nomeInstrumento);
                if (instrumento == null) {
                    throw new SQLException("Falha ao recuperar o ID do instrumento recém-cadastrado.");
                }
            }

            // 2. Buscar o Fornecedor pelo nome
            FornecedorDTO fornecedor = fornecedorImpl.buscarPorNome(nomeFornecedor);
            if (fornecedor == null) {
                JOptionPane.showMessageDialog(this, "Fornecedor '" + nomeFornecedor + "' não encontrado. Por favor, cadastre o fornecedor primeiro ou insira um nome válido.", "Fornecedor Não Encontrado", JOptionPane.WARNING_MESSAGE);
                logger.log(Level.WARNING, "Tentativa de cadastrar produto com fornecedor inexistente: " + nomeFornecedor);
                return;
            }

            // 3. Criar e Salvar o Produto
            ProdutoDTO produto = new ProdutoDTO();
            produto.setDescricao(descricao);
            produto.setModelo(modelo);
            produto.setMarca(marca);
            produto.setPreco(preco);
            produto.setQuantidadeEstoque(quantidade);
            produto.setIdInstrumento(instrumento.getIdInstrumento()); // Usa o ID do instrumento (existente ou novo)
            produto.setIdFornecedor(fornecedor.getId()); // Usa o ID do fornecedor

            produtoImpl.salvar(produto);

            JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            logger.log(Level.INFO, "Produto cadastrado com sucesso: " + nomeInstrumento + " - Modelo: " + modelo);
            limparCampos(); // Limpa os campos após o sucesso
            dispose(); // Fecha o JDialog
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Categoria inválida selecionada. Por favor, selecione uma categoria válida.", "Erro de Categoria", JOptionPane.ERROR_MESSAGE);
            logger.log(Level.SEVERE, "Erro ao converter categoria no cadastro de produto: " + categoria, e);
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, "Erro SQL ao cadastrar produto: " + ex.getMessage(), ex);
            JOptionPane.showMessageDialog(this, "Erro ao interagir com o banco de dados: " + ex.getMessage(), "Erro de Banco de Dados", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Ocorreu um erro inesperado ao salvar o produto: " + ex.getMessage(), ex);
            JOptionPane.showMessageDialog(this, "Ocorreu um erro inesperado ao salvar o produto: " + ex.getMessage(), "Erro Inesperado", JOptionPane.ERROR_MESSAGE);
        }
    }
//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * Método auxiliar para limpar os campos do formulário.
     */
    private void limparCampos() {
        txtNome.setText("");
        comBoxCategoria.setSelectedIndex(0);
        txtDescricao.setText("");
        txtModelo1.setText("");
        txtMarca.setText("");
        txtPreco.setText("");
        txtQuantidade.setText("");
        txtFornecedor.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cadastrarProduto dialog = new cadastrarProduto(new JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> comBoxCategoria;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo1;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
