/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.roncolatoandpedro.soulinstruments.ui;

import com.roncolatoandpedro.soulinstruments.dao.DAOFactory; // Importe DAOFactory
import com.roncolatoandpedro.soulinstruments.dao.impl.InstrumentoDAOImpl;
import com.roncolatoandpedro.soulinstruments.dto.Categoria;
import com.roncolatoandpedro.soulinstruments.dto.InstrumentoDTO;

import javax.swing.*;
import java.sql.Connection; // Importe Connection
import java.sql.SQLException;
import java.util.logging.Level; // Importe Level para uso com logger
import java.util.logging.Logger; // Importe Logger

/**
 *
 * @author AmonA
 */
public class cadastrarInstrumento extends javax.swing.JDialog {

    private static final Logger logger = Logger.getLogger(cadastrarInstrumento.class.getName());

    // A instância da DAO para instrumentos
    private InstrumentoDAOImpl instrumentoImpl;

    /**
     * Creates new form NewJDialog
     * @param parent O Frame pai do diálogo.
     * @param modal Define se o diálogo é modal (bloqueia a interação com a janela pai).
     */
    public cadastrarInstrumento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        try {
            // Inicializa a DAO de Instrumento usando a fábrica de conexões.
            // É fundamental que DAOFactory.getConexao() retorne uma Connection válida.
            Connection connection = DAOFactory.getConexao();
            this.instrumentoImpl = new InstrumentoDAOImpl(connection);
        } catch (SQLException e) {
            // Se houver um erro ao obter a conexão ou inicializar a DAO,
            // registre o erro e informe o usuário.
            logger.log(Level.SEVERE, "Erro ao inicializar InstrumentoDAOImpl: " + e.getMessage(), e);
            JOptionPane.showMessageDialog(this,
                    "Erro ao conectar ao banco de dados para o cadastro de instrumento: " + e.getMessage(),
                    "Erro de Inicialização",
                    JOptionPane.ERROR_MESSAGE);
            // Opcional: Se a conexão for crítica, você pode querer fechar o diálogo.
            // dispose();
        }

        // Popula o JComboBox com os valores da enum Categoria
        comBoxCategoria.removeAllItems();
        for (Categoria categoria : Categoria.values()) {
            comBoxCategoria.addItem(categoria.name());
        }
        comBoxCategoria.setSelectedIndex(0); // Seleciona o primeiro item por padrão

        // Removidos os setEnabled(false) nos campos de entrada
        // pois em um diálogo de cadastro, os campos devem estar habilitados
        // para que o usuário possa inserir os dados.
        // Se houver uma lógica específica para habilitar/desabilitar,
        // isso deve ser implementado via listeners ou outros métodos.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comBoxCategoria = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(40, 34, 44));

        jLabel5.setBackground(new java.awt.Color(21, 22, 27));
        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NOME");

        txtNome.setBackground(new java.awt.Color(22, 21, 27));
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(21, 22, 27));
        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CATEGORIA");

        comBoxCategoria.setBackground(new java.awt.Color(21, 22, 27));
        comBoxCategoria.setForeground(new java.awt.Color(255, 255, 255));
        comBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOPRO", "CORDAS", "PERCUSSAO", "ELETRONICO" }));
        comBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxCategoriaActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(202, 207, 214));
        btnSalvar.setForeground(new java.awt.Color(4, 138, 129));
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt); // Removido try-catch aqui, pois o tratamento será no método
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(comBoxCategoria, 0, 205, Short.MAX_VALUE)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5)
                                                .addComponent(txtNome)))
                                .addContainerGap(909, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1236, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 512, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void comBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxCategoriaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) { // Removido 'throws SQLException'
        // Verifica se a DAO foi inicializada corretamente
        if (instrumentoImpl == null) {
            JOptionPane.showMessageDialog(this, "O serviço de banco de dados não foi inicializado corretamente.", "Erro Interno", JOptionPane.ERROR_MESSAGE);
            logger.log(Level.SEVERE, "instrumentoImpl é nulo no btnSalvarActionPerformed. Verifique a inicialização no construtor.");
            return;
        }

        String nome = txtNome.getText();
        String categoriaSelecionada = (String) comBoxCategoria.getSelectedItem();

        // Validação de campos vazios
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo Nome não pode estar vazio!", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
            logger.log(Level.WARNING, "Tentativa de salvar instrumento com nome vazio.");
            return;
        }
        if (categoriaSelecionada == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma categoria para o instrumento!", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
            logger.log(Level.WARNING, "Tentativa de salvar instrumento sem categoria selecionada.");
            return;
        }

        // Criação do objeto DTO
        InstrumentoDTO instrumento = new InstrumentoDTO();
        instrumento.setNome(nome);
        try {
            instrumento.setCategoria(Categoria.valueOf(categoriaSelecionada));
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Categoria inválida selecionada. Por favor, selecione uma categoria válida.", "Erro de Categoria", JOptionPane.ERROR_MESSAGE);
            logger.log(Level.SEVERE, "Erro ao converter categoria: " + categoriaSelecionada, e);
            return;
        }


        // Salvar no banco
        try {
            instrumentoImpl.salvar(instrumento);
            JOptionPane.showMessageDialog(this, "Instrumento cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            logger.log(Level.INFO, "Instrumento cadastrado com sucesso: " + nome + " - Categoria: " + categoriaSelecionada);
            dispose(); // Fecha o JDialog após salvar
        } catch (SQLException ex) {
            // Erro ao salvar no banco de dados
            logger.log(Level.SEVERE, "Erro SQL ao salvar instrumento: " + ex.getMessage(), ex);
            JOptionPane.showMessageDialog(this, "Erro ao salvar instrumento no banco de dados: " + ex.getMessage(), "Erro de Banco de Dados", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            // Captura qualquer outra exceção inesperada
            logger.log(Level.SEVERE, "Ocorreu um erro inesperado ao salvar o instrumento: " + ex.getMessage(), ex);
            JOptionPane.showMessageDialog(this, "Ocorreu um erro inesperado ao salvar o instrumento: " + ex.getMessage(), "Erro Inesperado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastrarInstrumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastrarInstrumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastrarInstrumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastrarInstrumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cadastrarInstrumento dialog = new cadastrarInstrumento(new JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> comBoxCategoria;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
